def getStopWords():
        STOP_WORDS = frozenset([
                "a", "about", "above", "across", "after", "afterwards", "again", "against",
                "all", "almost", "alone", "along", "already", "also", "although", "always",
                "am", "among", "amongst", "amoungst", "amount", "an", "and", "another",
                "any", "anyhow", "anyone", "anything", "anyway", "anywhere", "are",
                "around", "as", "at", "back", "be", "became", "because", "become",
                "becomes", "becoming", "been", "before", "beforehand", "behind", "being",
                "below", "beside", "besides", "between", "beyond", "bill", "both",
                "bottom", "but", "by", "call", "can", "cannot", "cant", "co", "con",
                "could", "couldnt", "cry", "de", "describe", "detail", "do", "done",
                "down", "due", "during", "each", "eg", "eight", "either", "eleven", "else",
                "elsewhere", "empty", "enough", "etc", "even", "ever", "every", "everyone",
                "everything", "everywhere", "except", "few", "fifteen", "fifty", "fill",
                "find", "fire", "first", "five", "for", "former", "formerly", "forty",
                "found", "four", "from", "front", "full", "further", "get", "give", "go",
                "had", "has", "hasnt", "have", "he", "hence", "her", "here", "hereafter",
                "hereby", "herein", "hereupon", "hers", "herself", "him", "himself", "his",
                "how", "however", "hundred", "i", "ie", "if", "in", "inc", "indeed",
                "interest", "into", "is", "it", "its", "itself", "keep", "last", "latter",
                "latterly", "least", "less", "ltd", "made", "many", "may", "me",
                "meanwhile", "might", "mill", "mine", "more", "moreover", "most", "mostly",
                "move", "much", "must", "my", "myself", "name", "namely", "neither",
                "never", "nevertheless", "next", "nine", "no", "nobody", "none", "noone",
                "nor", "not", "nothing", "now", "nowhere", "of", "off", "often", "on",
                "once", "one", "only", "onto", "or", "other", "others", "otherwise", "our",
                "ours", "ourselves", "out", "over", "own", "part", "per", "perhaps",
                "please", "put", "rather", "re", "same", "see", "seem", "seemed",
                "seeming", "seems", "serious", "several", "she", "should", "show", "side",
                "since", "sincere", "six", "sixty", "so", "some", "somehow", "someone",
                "something", "sometime", "sometimes", "somewhere", "still", "such",
                "system", "take", "ten", "than", "that", "the", "their", "them",
                "themselves", "then", "thence", "there", "thereafter", "thereby",
                "therefore", "therein", "thereupon", "these", "they", "thick", "thin",
                "third", "this", "those", "though", "three", "through", "throughout",
                "thru", "thus", "to", "together", "too", "top", "toward", "towards",
                "twelve", "twenty", "two", "un", "under", "until", "up", "upon", "us",
                "very", "via", "was", "we", "well", "were", "what", "whatever", "when",
                "whence", "whenever", "where", "whereafter", "whereas", "whereby",
                "wherein", "whereupon", "wherever", "whether", "which", "while", "whither",
                "who", "whoever", "whole", "whom", "whose", "why", "will", "with",
                "within", "without", "would", "yet", "you", "your", "yours", "yourself",
                "yourselves", "这个", "那个", "这", "那", "也", "就是", "开始", "这么",
                "什么", "但是", "如果", "出来", "现在", "一切", "曾经", "听到", "可以",
                "很多", "不是", "你们", "我们", "不要", "一定", "然后", "想要", "感觉",
                "别人", "以前", "告诉", "昨天", "明天", "今天", "还是", "为什么", "回来",
                "刚好", "只能", "错过", "我们", "你们", "他们", "觉得", "每个", "事情",
                "一点", "一样", "一种", "怎么", "应该", "前进", "终于", "已经", "第一次",
                "如果", "就是", "可能", "再也", "结果", "这里", "一次", "之前", "真的",
                "不能", "再见", "只是", "一下", "那么", "不在", "可是", "一直", "以为",
                "不再", "其实", "首歌", "大家", "相信", "哈哈哈", "一个", "时候", "为了",
                "一起", "只有", "遇到", "最后", "想起", "还有", "因为", "不如", "亲亲",
                "找到", "也许", "出现", "不会", "这样", "不过", "没有", "知道", "所以",
                "一天", "这些", "我要"])
        return STOP_WORDS

